services:
  foodgram_db:
    env_file: .env
    image: postgres:14-alpine
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data
    networks:
      - foodgram_network

  foodgram_backend:
    env_file: .env
    depends_on:
      - foodgram_db
    image: ram0k009/foodgram_backend:latest
    volumes:
      - foodgram_static:/app/backend_static
      - foodgram_media:/app/media
    networks:
      - foodgram_network

  foodgram_frontend:
    env_file: .env
    depends_on:
      - foodgram_backend
    image: ram0k009/foodgram_frontend:latest
    command: cp -r /app/build/. /app/frontend_static/
    volumes:
      - foodgram_static:/app/frontend_static
    networks:
      - foodgram_network

  foodgram_gateway:
    depends_on:
      - foodgram_frontend
      - foodgram_backend
    image: ram0k009/foodgram_gateway:latest
    volumes:
      - foodgram_static:/staticfiles
      - foodgram_media:/media
    networks:
      - foodgram_network
    ports:
      - "80:80"

networks:
  foodgram_network:
    driver: bridge

volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media: